---
- hosts: server
  become: true
  gather_facts: no
  
  vars:
    pass_mysql: lookup('env', 'PASS_MYSQL')

  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: sudo apt-get upgrade && sudo apt-get -y install python-simplejson
    # action: setup will gather facts after python2 has been installed
    - action: setup
  
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes
    
    - name: Install git
      apt: pkg=git state=present

    - name: Install NodeJS and npm
      apt: name={{ item }} state=present
      with_items:
        - nodejs
        - nodejs-dev
        - nodejs-legacy
        - npm
        - unzip
        
    - name: Install pm2 for manage our nodejs application
      npm:
        name: pm2
        global: yes
    
    - name: Install MySQL
      apt: pkg=mysql-server state=present
    
    - name: Clone repo
      git: repo=https://github.com/JPPorcel/ServerMusic.git dest=/opt/app version=HEAD
      
    - name: Install dependencies with npm
      shell: "cd /opt/app && sudo npm install"
      
    - name: Load database
      shell: "cd /opt/app/mysql && mysql < modelo.sql && mysql Music < autores.sql && mysql Music < marchas.sql && mysql Music < localidades.sql"
      
    #- name: Run server as a ubuntu service
      #shell: 'cp /opt/app/provision/server_music.service /etc/systemd/system/server_music.service && systemctl daemon-reload && systemctl enable server_music && systemctl start server_music'
      
    - name: Run server with pm2
      shell: 'cd /opt/app && pm2 start server.js && pm2 startup'
      
    - name: Install nginx
      apt: pkg=nginx state=present
      
    - name: Configure nginx
      shell: 'cd /opt/app/provision && cp sites-available_default /etc/nginx/sites-available/default && sudo service nginx restart'
